### PR TITLE
Update to 0.11.0

### PR DESCRIPTION
**Pull request by wcarss**

### CODE REVIEW

**Review by marcus-daily — APPROVED** [review]
@wcarss This LGTM -- let me know if we also want the code changes (including screen sharing) though and I can add these.

**Comment by wcarss** [comment]
yes please!

**Comment by marcus-daily** [comment]
Done :) I've also added @filipi87 as a reviewer for the screen share bits.

**Review by filipi87 — APPROVED** [review]
I haven't tested it, but based on the changes, it appears that we have everything we need to make the screen share work.

**Comment by marcus-daily** [comment]
Thanks @filipi87! I've tested a local build and the APK from the CI, will merge this in.

**Pull request merged**
