### PR TITLE
Upgrade to daily-android 0.7.0

### PR DESCRIPTION
**Pull request by marcus-daily**

### CODE REVIEW

**Comment by marcus-daily** [comment]
CI currently failing because 0.7.0 isn't published yet.

**Comment by filipi87** [comment]
We need to use this SDK in order to work fine: https://github.com/daily-co/daily-x/actions/runs/4316614127

**Review by filipi87 — APPROVED** [review]
LGTM!

**Review by wcarss — APPROVED** [review]
tested with newly-published 0.7.1, 👍

**Pull request merged**
